project:
  type: website

website:
  title: "do4ds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model-db.qmd
      - eda-db.qmd
      - classification.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto