---
title: "Penguins EDA"
format:
  html:
    code-fold: true
---

## *Penguin Size and Mass by Sex and Species*

```{r message=FALSE}
library(dplyr)
library(ggplot2)
library(dbplyr)

con <- DBI::dbConnect(
  duckdb::duckdb(), 
  dbdir = "my-db.duckdb"
  )
df <- dplyr::tbl(con, "penguins")
```

```{r message=FALSE, warning=FALSE}
df %>%
  group_by(species, sex) %>%
  summarise(
    across(
        ends_with("mm") | ends_with("g"),
      \(x) mean(x, na.rm = TRUE)
      )
    ) %>%
  dplyr::collect() %>%
  knitr::kable()
```

## *Penguin Mass vs Bill Length by Species*

```{r warning=FALSE, message=FALSE}
df %>%
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() + 
  geom_smooth(method = "lm")+
  labs(x = "Bill Length (mm)", y = "Body Mass (g)", title = "Penguin Size vs Bill Length by Species")
```

```{r warning=FALSE, message=FALSE}

ggplot(df, aes(x = species, y = body_mass_g, fill = species)) + 
  geom_boxplot() +
  scale_fill_manual(values=c("Adelie"="red", "Chinstrap"="green", "Gentoo"="blue")) +
  labs(x = "Species", y = "Body Mass (g)", title = "Box Plot of Penguin Body Mass by Species")
```

```{r}
DBI::dbDisconnect(con)
```
